// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ItemType.
const (
	Good    ItemType = "good"
	Service ItemType = "service"
)

// Valid indicates whether the value is a known member of the ItemType enum.
func (e ItemType) Valid() bool {
	switch e {
	case Good:
		return true
	case Service:
		return true
	default:
		return false
	}
}

// Defines values for OfferAction.
const (
	Give OfferAction = "give"
	Take OfferAction = "take"
)

// Valid indicates whether the value is a known member of the OfferAction enum.
func (e OfferAction) Valid() bool {
	switch e {
	case Give:
		return true
	case Take:
		return true
	default:
		return false
	}
}

// Defines values for SortType.
const (
	SortTypeByPopularity SortType = "ByPopularity"
	SortTypeByTime       SortType = "ByTime"
)

// Valid indicates whether the value is a known member of the SortType enum.
func (e SortType) Valid() bool {
	switch e {
	case SortTypeByPopularity:
		return true
	case SortTypeByTime:
		return true
	default:
		return false
	}
}

// Defines values for ListOffersParamsSort.
const (
	ListOffersParamsSortByPopularity ListOffersParamsSort = "ByPopularity"
	ListOffersParamsSortByTime       ListOffersParamsSort = "ByTime"
)

// Valid indicates whether the value is a known member of the ListOffersParamsSort enum.
func (e ListOffersParamsSort) Valid() bool {
	switch e {
	case ListOffersParamsSortByPopularity:
		return true
	case ListOffersParamsSortByTime:
		return true
	default:
		return false
	}
}

// ConfirmDraftDealResponse defines model for ConfirmDraftDealResponse.
type ConfirmDraftDealResponse struct {
	// Users Список пользователей, которые подтвердили/не подтвердили свое участие в сделке
	Users []UserConfirm `json:"users"`
}

// CreateDraftDealRequest defines model for CreateDraftDealRequest.
type CreateDraftDealRequest struct {
	// Description An optional description for the draft deal
	Description *string `json:"description,omitempty"`

	// Name An optional name for the draft deal
	Name   *string              `json:"name,omitempty"`
	Offers []OfferIDAndQuantity `json:"offers"`
}

// CreateDraftDealResponse defines model for CreateDraftDealResponse.
type CreateDraftDealResponse struct {
	// Id The unique identifier of the created draft deal
	Id openapi_types.UUID `json:"id"`
}

// CreateOfferRequest defines model for CreateOfferRequest.
type CreateOfferRequest struct {
	// Action Whether the user offers or requests something
	Action      OfferAction `json:"action"`
	Description string      `json:"description"`
	Name        string      `json:"name"`

	// Type Type of barter item
	Type ItemType `json:"type"`
}

// Deal defines model for Deal.
type Deal struct {
	// CreatedAt Временная метка создания сделки
	CreatedAt time.Time `json:"createdAt"`

	// Description Описание сделки
	Description *string `json:"description,omitempty"`

	// Id Уникальный идентификатор сделки
	Id openapi_types.UUID `json:"id"`

	// Items Список позиций сделки
	Items []Item `json:"items"`

	// Name Название сделки
	Name *string `json:"name,omitempty"`

	// UpdatedAt Временная метка последнего обновления сделки
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Draft defines model for Draft.
type Draft struct {
	// AuthorId The unique identifier of the user who created the draft deal
	AuthorId openapi_types.UUID `json:"authorId"`

	// CreatedAt The timestamp when the draft deal was created
	CreatedAt time.Time `json:"createdAt"`

	// Description A detailed description of the draft deal
	Description *string `json:"description,omitempty"`

	// Id The unique identifier of the draft deal
	Id openapi_types.UUID `json:"id"`

	// Name The name of the draft deal
	Name *string `json:"name,omitempty"`

	// Offers A list of offers included in the draft deal
	Offers []OfferWithInfo `json:"offers"`

	// UpdatedAt The timestamp when the draft deal was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// GetDealsResponse defines model for GetDealsResponse.
type GetDealsResponse = []GetDealsResponseItem

// GetDealsResponseItem defines model for GetDealsResponseItem.
type GetDealsResponseItem struct {
	// Id Уникальный идентификатор сделки
	Id openapi_types.UUID `json:"id"`

	// Participants Список ID всех пользователей, участвующих в этой сделке
	Participants []openapi_types.UUID `json:"participants"`
}

// GetMyDraftDealsResponse defines model for GetMyDraftDealsResponse.
type GetMyDraftDealsResponse = []GetMyDraftDealsResponseItem

// GetMyDraftDealsResponseItem defines model for GetMyDraftDealsResponseItem.
type GetMyDraftDealsResponseItem struct {
	// Id Уникальный идентификатор черновой сделки
	Id openapi_types.UUID `json:"id"`

	// Participants Список ID всех пользователей, участвующих в этой сделке
	Participants []openapi_types.UUID `json:"participants"`
}

// Item defines model for Item.
type Item struct {
	// AuthorId Уникальный идентификатор пользователя, который предложил эту позицию в сделке
	AuthorId openapi_types.UUID `json:"authorId"`

	// Description Подробное описание позиции сделки
	Description string `json:"description"`

	// Id Уникальный идентификатор позиции сделки
	Id openapi_types.UUID `json:"id"`

	// Name Краткое название позиции сделки
	Name string `json:"name"`

	// ProviderId Уникальный идентификатор пользователя, который отдает эту позицию в сделке
	ProviderId *openapi_types.UUID `json:"providerId,omitempty"`

	// Quantity Количество позиций этого типа в сделке
	Quantity int `json:"quantity"`

	// ReceiverId Уникальный идентификатор пользователя, который получает эту позицию в сделке
	ReceiverId *openapi_types.UUID `json:"receiverId,omitempty"`

	// Type Type of barter item
	Type ItemType `json:"type"`

	// UpdatedAt Временная метка последнего обновления позиции сделки
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// ItemType Type of barter item
type ItemType string

// ListOffersResponse defines model for ListOffersResponse.
type ListOffersResponse struct {
	// NextCursor Cursor for fetching the next page; null if there is no next page
	NextCursor *OffersCursor `json:"nextCursor,omitempty"`

	// Offers List of offers
	Offers []Offer `json:"offers"`
}

// Offer defines model for Offer.
type Offer struct {
	// Action Whether the user offers or requests something
	Action OfferAction `json:"action"`

	// AuthorId Unique identifier of the user who created the item
	AuthorId openapi_types.UUID `json:"authorId"`

	// AuthorName Name of the user who created the item
	AuthorName *string `json:"authorName,omitempty"`

	// CreatedAt Item creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Description Detailed item description
	Description string `json:"description"`

	// Id Unique item identifier
	Id openapi_types.UUID `json:"id"`

	// Name Short item title
	Name string `json:"name"`

	// Type Type of barter item
	Type ItemType `json:"type"`

	// Views Number of item views
	Views int64 `json:"views"`
}

// OfferAction Whether the user offers or requests something
type OfferAction string

// OfferIDAndQuantity defines model for OfferIDAndQuantity.
type OfferIDAndQuantity struct {
	// OfferID The ID of the offer to include in the draft deal
	OfferID openapi_types.UUID `json:"offerID"`

	// Quantity The quantity of the offer to include in the draft deal
	Quantity int `json:"quantity"`
}

// OfferInfo defines model for OfferInfo.
type OfferInfo struct {
	// Confirmed Whether the offer has been confirmed for the draft deal.
	Confirmed *bool `json:"confirmed,omitempty"`

	// Quantity The quantity of the offer to include in the draft deal
	Quantity int `json:"quantity"`
}

// OfferWithInfo defines model for OfferWithInfo.
type OfferWithInfo struct {
	// Action Whether the user offers or requests something
	Action OfferAction `json:"action"`

	// AuthorId Unique identifier of the user who created the item
	AuthorId openapi_types.UUID `json:"authorId"`

	// AuthorName Name of the user who created the item
	AuthorName *string `json:"authorName,omitempty"`

	// Confirmed Whether the offer has been confirmed for the draft deal.
	Confirmed *bool `json:"confirmed,omitempty"`

	// CreatedAt Item creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Description Detailed item description
	Description string `json:"description"`

	// Id Unique item identifier
	Id openapi_types.UUID `json:"id"`

	// Name Short item title
	Name string `json:"name"`

	// Quantity The quantity of the offer to include in the draft deal
	Quantity int `json:"quantity"`

	// Type Type of barter item
	Type ItemType `json:"type"`

	// Views Number of item views
	Views int64 `json:"views"`
}

// OffersCursor Cursor for stable pagination
type OffersCursor struct {
	CreatedAt *time.Time         `json:"createdAt,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Views     *int64             `json:"views,omitempty"`
}

// UserConfirm defines model for UserConfirm.
type UserConfirm struct {
	// Confirmed Статус подтверждения участия пользователя в сделке
	Confirmed bool `json:"confirmed"`

	// UserId Уникальный идентификатор пользователя
	UserId openapi_types.UUID `json:"userId"`
}

// CursorCreatedAt defines model for CursorCreatedAt.
type CursorCreatedAt = time.Time

// CursorId defines model for CursorId.
type CursorId = openapi_types.UUID

// CursorViews defines model for CursorViews.
type CursorViews = int64

// Limit defines model for Limit.
type Limit = int

// SortType defines model for SortType.
type SortType string

// GetDealsParams defines parameters for GetDeals.
type GetDealsParams struct {
	// My False by default. Если true, возвращает только сделки, в которых текущий пользователь является участником
	My *bool `form:"my,omitempty" json:"my,omitempty"`

	// Open False by default. Если true, возвращает только открытые сделки
	Open *bool `form:"open,omitempty" json:"open,omitempty"`
}

// GetMyDraftDealsParams defines parameters for GetMyDraftDeals.
type GetMyDraftDealsParams struct {
	CreatedByMe   *bool `form:"createdByMe,omitempty" json:"createdByMe,omitempty"`
	Participating *bool `form:"participating,omitempty" json:"participating,omitempty"`
}

// ListOffersParams defines parameters for ListOffers.
type ListOffersParams struct {
	// My False by default. If true, returns only offers created by the current user.
	My *bool `form:"my,omitempty" json:"my,omitempty"`

	// Sort Sorting mode for items list
	Sort ListOffersParamsSort `form:"sort" json:"sort"`

	// CursorCreatedAt Cursor creation timestamp in RFC3339 format.
	// Used together with `cursor_id` when `sort=created_at`.
	CursorCreatedAt *CursorCreatedAt `form:"cursor_created_at,omitempty" json:"cursor_created_at,omitempty"`

	// CursorViews Cursor views count.
	// Used together with `cursor_id` when `sort=popularity`.
	CursorViews *CursorViews `form:"cursor_views,omitempty" json:"cursor_views,omitempty"`

	// CursorId Cursor item ID used as a tie-breaker for stable pagination.
	CursorId *CursorId `form:"cursor_id,omitempty" json:"cursor_id,omitempty"`

	// CursorLimit Maximum number of items to return
	CursorLimit *Limit `form:"cursor_limit,omitempty" json:"cursor_limit,omitempty"`
}

// ListOffersParamsSort defines parameters for ListOffers.
type ListOffersParamsSort string

// UpdateDealItemRequest defines model for UpdateDealItemRequest.
type UpdateDealItemRequest struct {
	// Description Новое описание позиции
	Description *string `json:"description,omitempty"`

	// Name Новое название позиции
	Name *string `json:"name,omitempty"`

	// Quantity Новое количество
	Quantity *int `json:"quantity,omitempty"`
}

// UpdateDealItemParams defines parameters for UpdateDealItem.
type UpdateDealItemParams struct {
	DealId openapi_types.UUID `json:"dealId"`
	ItemId openapi_types.UUID `json:"itemId"`
}

// UpdateDealItemJSONRequestBody defines body for UpdateDealItem for application/json ContentType.
type UpdateDealItemJSONRequestBody = UpdateDealItemRequest

// CreateDraftDealJSONRequestBody defines body for CreateDraftDeal for application/json ContentType.
type CreateDraftDealJSONRequestBody = CreateDraftDealRequest

// CreateOffersJSONRequestBody defines body for CreateOffers for application/json ContentType.
type CreateOffersJSONRequestBody = CreateOfferRequest
