// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ItemAction.
const (
	Give ItemAction = "give"
	Take ItemAction = "take"
)

// Valid indicates whether the value is a known member of the ItemAction enum.
func (e ItemAction) Valid() bool {
	switch e {
	case Give:
		return true
	case Take:
		return true
	default:
		return false
	}
}

// Defines values for ItemType.
const (
	Good    ItemType = "good"
	Service ItemType = "service"
)

// Valid indicates whether the value is a known member of the ItemType enum.
func (e ItemType) Valid() bool {
	switch e {
	case Good:
		return true
	case Service:
		return true
	default:
		return false
	}
}

// Defines values for SortType.
const (
	SortTypeByPopularity SortType = "ByPopularity"
	SortTypeByTime       SortType = "ByTime"
)

// Valid indicates whether the value is a known member of the SortType enum.
func (e SortType) Valid() bool {
	switch e {
	case SortTypeByPopularity:
		return true
	case SortTypeByTime:
		return true
	default:
		return false
	}
}

// Defines values for ListItemsParamsSort.
const (
	ListItemsParamsSortByPopularity ListItemsParamsSort = "ByPopularity"
	ListItemsParamsSortByTime       ListItemsParamsSort = "ByTime"
)

// Valid indicates whether the value is a known member of the ListItemsParamsSort enum.
func (e ListItemsParamsSort) Valid() bool {
	switch e {
	case ListItemsParamsSortByPopularity:
		return true
	case ListItemsParamsSortByTime:
		return true
	default:
		return false
	}
}

// ConfirmDraftDealResponse defines model for ConfirmDraftDealResponse.
type ConfirmDraftDealResponse struct {
	// Users Список пользователей, которые подтвердили/не подтвердили свое участие в сделке
	Users []struct {
		// Confirmed Статус подтверждения участия пользователя в сделке
		Confirmed bool `json:"confirmed"`

		// UserId Уникальный идентификатор пользователя
		UserId openapi_types.UUID `json:"userId"`
	} `json:"users"`
}

// CreateDraftDealRequest defines model for CreateDraftDealRequest.
type CreateDraftDealRequest struct {
	// Description An optional description for the draft deal
	Description *string `json:"description,omitempty"`
	Items       []struct {
		// ItemID The ID of the item to include in the draft deal
		ItemID openapi_types.UUID `json:"itemID"`

		// Quantity The quantity of the item to include in the draft deal
		Quantity int `json:"quantity"`

		// ReceiverID The ID of the user who will receive this item in the deal.
		// If not provided, it is assumed that the item is offered by the current user
		// and any of other participants may choose to be a receiver.
		ReceiverID *openapi_types.UUID `json:"receiverID,omitempty"`
	} `json:"items"`

	// Name An optional name for the draft deal
	Name *string `json:"name,omitempty"`
}

// CreateDraftDealResponse defines model for CreateDraftDealResponse.
type CreateDraftDealResponse struct {
	// Id The unique identifier of the created draft deal
	Id openapi_types.UUID `json:"id"`
}

// CreateItemRequest defines model for CreateItemRequest.
type CreateItemRequest struct {
	// Action Whether the user offers or requests something
	Action      ItemAction `json:"action"`
	Description string     `json:"description"`
	Name        string     `json:"name"`

	// Type Type of barter item
	Type ItemType `json:"type"`
}

// Draft defines model for Draft.
type Draft struct {
	// AuthorId The unique identifier of the user who created the draft deal
	AuthorId openapi_types.UUID `json:"authorId"`

	// CreatedAt The timestamp when the draft deal was created
	CreatedAt time.Time `json:"createdAt"`

	// Description A detailed description of the draft deal
	Description *string `json:"description,omitempty"`

	// Id The unique identifier of the draft deal
	Id openapi_types.UUID `json:"id"`

	// Items A list of items included in the draft deal
	Items []Item `json:"items"`

	// Name The name of the draft deal
	Name *string `json:"name,omitempty"`

	// UpdatedAt The timestamp when the draft deal was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// GetMyDraftDealsResponse defines model for GetMyDraftDealsResponse.
type GetMyDraftDealsResponse struct {
	Data *[]openapi_types.UUID `json:"data,omitempty"`
}

// Item defines model for Item.
type Item struct {
	// Action Whether the user offers or requests something
	Action ItemAction `json:"action"`

	// AuthorId Unique identifier of the user who created the item
	AuthorId openapi_types.UUID `json:"authorId"`

	// CreatedAt Item creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Description Detailed item description
	Description string `json:"description"`

	// Id Unique item identifier
	Id openapi_types.UUID `json:"id"`

	// Name Short item title
	Name string `json:"name"`

	// Type Type of barter item
	Type ItemType `json:"type"`

	// Views Number of item views
	Views int64 `json:"views"`
}

// ItemAction Whether the user offers or requests something
type ItemAction string

// ItemType Type of barter item
type ItemType string

// ItemsCursor Cursor for stable pagination
type ItemsCursor struct {
	CreatedAt *time.Time         `json:"createdAt,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Views     *int64             `json:"views,omitempty"`
}

// ListItemsResponse defines model for ListItemsResponse.
type ListItemsResponse struct {
	// Items List of items
	Items []Item `json:"items"`

	// NextCursor Cursor for fetching the next page; null if there is no next page
	NextCursor *ItemsCursor `json:"nextCursor,omitempty"`
}

// CursorCreatedAt defines model for CursorCreatedAt.
type CursorCreatedAt = time.Time

// CursorId defines model for CursorId.
type CursorId = openapi_types.UUID

// CursorViews defines model for CursorViews.
type CursorViews = int64

// Limit defines model for Limit.
type Limit = int

// SortType defines model for SortType.
type SortType string

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	// Sort Sorting mode for items list
	Sort ListItemsParamsSort `form:"sort" json:"sort"`

	// CursorCreatedAt Cursor creation timestamp in RFC3339 format.
	// Used together with `cursor_id` when `sort=created_at`.
	CursorCreatedAt *CursorCreatedAt `form:"cursor_created_at,omitempty" json:"cursor_created_at,omitempty"`

	// CursorViews Cursor views count.
	// Used together with `cursor_id` when `sort=popularity`.
	CursorViews *CursorViews `form:"cursor_views,omitempty" json:"cursor_views,omitempty"`

	// CursorId Cursor item ID used as a tie-breaker for stable pagination.
	CursorId *CursorId `form:"cursor_id,omitempty" json:"cursor_id,omitempty"`

	// CursorLimit Maximum number of items to return
	CursorLimit *Limit `form:"cursor_limit,omitempty" json:"cursor_limit,omitempty"`
}

// ListItemsParamsSort defines parameters for ListItems.
type ListItemsParamsSort string

// CreateDraftDealJSONRequestBody defines body for CreateDraftDeal for application/json ContentType.
type CreateDraftDealJSONRequestBody = CreateDraftDealRequest

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = CreateItemRequest
