// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ItemType.
const (
	ItemTypeGood    ItemType = "itemTypeGood"
	ItemTypeService ItemType = "itemTypeService"
)

// Valid indicates whether the value is a known member of the ItemType enum.
func (e ItemType) Valid() bool {
	switch e {
	case ItemTypeGood:
		return true
	case ItemTypeService:
		return true
	default:
		return false
	}
}

// Defines values for OfferAction.
const (
	OfferActionGive OfferAction = "offerActionGive"
	OfferActionTake OfferAction = "offerActionTake"
)

// Valid indicates whether the value is a known member of the OfferAction enum.
func (e OfferAction) Valid() bool {
	switch e {
	case OfferActionGive:
		return true
	case OfferActionTake:
		return true
	default:
		return false
	}
}

// Defines values for SortType.
const (
	SortTypeByPopularity SortType = "ByPopularity"
	SortTypeByTime       SortType = "ByTime"
)

// Valid indicates whether the value is a known member of the SortType enum.
func (e SortType) Valid() bool {
	switch e {
	case SortTypeByPopularity:
		return true
	case SortTypeByTime:
		return true
	default:
		return false
	}
}

// Defines values for ListOffersParamsSort.
const (
	ListOffersParamsSortByPopularity ListOffersParamsSort = "ByPopularity"
	ListOffersParamsSortByTime       ListOffersParamsSort = "ByTime"
)

// Valid indicates whether the value is a known member of the ListOffersParamsSort enum.
func (e ListOffersParamsSort) Valid() bool {
	switch e {
	case ListOffersParamsSortByPopularity:
		return true
	case ListOffersParamsSortByTime:
		return true
	default:
		return false
	}
}

// ConfirmDraftDealResponse defines model for ConfirmDraftDealResponse.
type ConfirmDraftDealResponse struct {
	// Users Список пользователей, которые подтвердили/не подтвердили свое участие в сделке
	Users []UserConfirm `json:"users"`
}

// CreateDraftDealRequest defines model for CreateDraftDealRequest.
type CreateDraftDealRequest struct {
	// Description An optional description for the draft deal
	Description *string `json:"description,omitempty"`

	// Name An optional name for the draft deal
	Name   *string              `json:"name,omitempty"`
	Offers []OfferIDAndQuantity `json:"offers"`
}

// CreateDraftDealResponse defines model for CreateDraftDealResponse.
type CreateDraftDealResponse struct {
	// Id The unique identifier of the created draft deal
	Id openapi_types.UUID `json:"id"`
}

// CreateOfferRequest defines model for CreateOfferRequest.
type CreateOfferRequest struct {
	// Action Whether the user offers or requests something
	Action      OfferAction `json:"action"`
	Description string      `json:"description"`
	Name        string      `json:"name"`

	// Type Type of barter item
	Type ItemType `json:"type"`
}

// Draft defines model for Draft.
type Draft struct {
	// AuthorId The unique identifier of the user who created the draft deal
	AuthorId openapi_types.UUID `json:"authorId"`

	// CreatedAt The timestamp when the draft deal was created
	CreatedAt time.Time `json:"createdAt"`

	// Description A detailed description of the draft deal
	Description *string `json:"description,omitempty"`

	// Id The unique identifier of the draft deal
	Id openapi_types.UUID `json:"id"`

	// Name The name of the draft deal
	Name *string `json:"name,omitempty"`

	// Offers A list of offers included in the draft deal
	Offers []OfferWithInfo `json:"offers"`

	// UpdatedAt The timestamp when the draft deal was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// GetMyDraftDealsResponse defines model for GetMyDraftDealsResponse.
type GetMyDraftDealsResponse struct {
	Data *[]openapi_types.UUID `json:"data,omitempty"`
}

// ItemType Type of barter item
type ItemType string

// ListOffersResponse defines model for ListOffersResponse.
type ListOffersResponse struct {
	// NextCursor Cursor for fetching the next page; null if there is no next page
	NextCursor *OffersCursor `json:"nextCursor,omitempty"`

	// Offers List of offers
	Offers []Offer `json:"offers"`
}

// Offer defines model for Offer.
type Offer struct {
	// Action Whether the user offers or requests something
	Action OfferAction `json:"action"`

	// AuthorId Unique identifier of the user who created the item
	AuthorId openapi_types.UUID `json:"authorId"`

	// CreatedAt Item creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Description Detailed item description
	Description string `json:"description"`

	// Id Unique item identifier
	Id openapi_types.UUID `json:"id"`

	// Name Short item title
	Name string `json:"name"`

	// Type Type of barter item
	Type ItemType `json:"type"`

	// Views Number of item views
	Views int64 `json:"views"`
}

// OfferAction Whether the user offers or requests something
type OfferAction string

// OfferIDAndQuantity defines model for OfferIDAndQuantity.
type OfferIDAndQuantity struct {
	// OfferID The ID of the offer to include in the draft deal
	OfferID openapi_types.UUID `json:"offerID"`

	// Quantity The quantity of the offer to include in the draft deal
	Quantity int `json:"quantity"`
}

// OfferInfo defines model for OfferInfo.
type OfferInfo struct {
	// Confirmed Whether the offer has been confirmed for the draft deal.
	Confirmed *bool `json:"confirmed,omitempty"`

	// Quantity The quantity of the offer to include in the draft deal
	Quantity int `json:"quantity"`
}

// OfferWithInfo defines model for OfferWithInfo.
type OfferWithInfo struct {
	// Action Whether the user offers or requests something
	Action OfferAction `json:"action"`

	// AuthorId Unique identifier of the user who created the item
	AuthorId openapi_types.UUID `json:"authorId"`

	// Confirmed Whether the offer has been confirmed for the draft deal.
	Confirmed *bool `json:"confirmed,omitempty"`

	// CreatedAt Item creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Description Detailed item description
	Description string `json:"description"`

	// Id Unique item identifier
	Id openapi_types.UUID `json:"id"`

	// Name Short item title
	Name string `json:"name"`

	// Quantity The quantity of the offer to include in the draft deal
	Quantity int `json:"quantity"`

	// Type Type of barter item
	Type ItemType `json:"type"`

	// Views Number of item views
	Views int64 `json:"views"`
}

// OffersCursor Cursor for stable pagination
type OffersCursor struct {
	CreatedAt *time.Time         `json:"createdAt,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Views     *int64             `json:"views,omitempty"`
}

// UserConfirm defines model for UserConfirm.
type UserConfirm struct {
	// Confirmed Статус подтверждения участия пользователя в сделке
	Confirmed bool `json:"confirmed"`

	// UserId Уникальный идентификатор пользователя
	UserId openapi_types.UUID `json:"userId"`
}

// CursorCreatedAt defines model for CursorCreatedAt.
type CursorCreatedAt = time.Time

// CursorId defines model for CursorId.
type CursorId = openapi_types.UUID

// CursorViews defines model for CursorViews.
type CursorViews = int64

// Limit defines model for Limit.
type Limit = int

// SortType defines model for SortType.
type SortType string

// ListOffersParams defines parameters for ListOffers.
type ListOffersParams struct {
	// Sort Sorting mode for items list
	Sort ListOffersParamsSort `form:"sort" json:"sort"`

	// CursorCreatedAt Cursor creation timestamp in RFC3339 format.
	// Used together with `cursor_id` when `sort=created_at`.
	CursorCreatedAt *CursorCreatedAt `form:"cursor_created_at,omitempty" json:"cursor_created_at,omitempty"`

	// CursorViews Cursor views count.
	// Used together with `cursor_id` when `sort=popularity`.
	CursorViews *CursorViews `form:"cursor_views,omitempty" json:"cursor_views,omitempty"`

	// CursorId Cursor item ID used as a tie-breaker for stable pagination.
	CursorId *CursorId `form:"cursor_id,omitempty" json:"cursor_id,omitempty"`

	// CursorLimit Maximum number of items to return
	CursorLimit *Limit `form:"cursor_limit,omitempty" json:"cursor_limit,omitempty"`
}

// ListOffersParamsSort defines parameters for ListOffers.
type ListOffersParamsSort string

// CreateDraftDealJSONRequestBody defines body for CreateDraftDeal for application/json ContentType.
type CreateDraftDealJSONRequestBody = CreateDraftDealRequest

// CreateOffersJSONRequestBody defines body for CreateOffers for application/json ContentType.
type CreateOffersJSONRequestBody = CreateOfferRequest
