package domain

import "errors"

var (
	ErrInvalidOfferName                 = errors.New("invalid offer name")
	ErrInvalidQuantity                  = errors.New("invalid quantity")
	ErrDraftNotFound                    = errors.New("draft not found")
	ErrDealNotFound                     = errors.New("deal not found")
	ErrItemNotFound                     = errors.New("item not found")
	ErrFailureNotFound                  = errors.New("failure not found")
	ErrNoOffers                         = errors.New("no offers")
	ErrOfferNotFound                    = errors.New("offer not found")
	ErrOfferGroupNotFound               = errors.New("offer group not found")
	ErrNoOfferGroupUnits                = errors.New("offer group must contain at least one unit")
	ErrEmptyOfferGroupUnit              = errors.New("offer group unit must contain at least one offer")
	ErrDuplicateOfferInGroup            = errors.New("offer is duplicated in offer group")
	ErrMixedOfferActionsInUnit          = errors.New("all offers in unit must have the same action")
	ErrInvalidOfferGroupSelect          = errors.New("invalid offer group selection")
	ErrOfferGroupResponderOfferRequired = errors.New("responder offer is required for this offer group")
	ErrOfferGroupResponderOfferAction   = errors.New("responder offer must have the same action")
	ErrUserNotInDraft                   = errors.New("user not in draft")
	ErrForbidden                        = errors.New("forbidden")
	ErrAdminOnly                        = errors.New("admin only")
	ErrRoleAlreadyTaken                 = errors.New("role already taken by another user")
	ErrNotRoleHolder                    = errors.New("user does not hold this role")
	ErrDuplicateRole                    = errors.New("user already holds this item with other role")
	ErrInvalidDealStatus                = errors.New("deal is not in the expected status")
	ErrFailureReviewRequired            = errors.New("deal is pending failure review")
	ErrFailureAlreadyResolved           = errors.New("failure already resolved")
	ErrInvalidFailureDecision           = errors.New("invalid failure decision")
	ErrJoinRequestNotFound              = errors.New("join request not found")
	ErrDealParticipantsUnready          = errors.New("deal participants unready")

	ErrReviewNotFound          = errors.New("review not found")
	ErrReviewAlreadyExists     = errors.New("review already exists")
	ErrReceiverMissing         = errors.New("item has no receiver")
	ErrProviderMissing         = errors.New("item has no provider")
	ErrSameProviderAndReceiver = errors.New("provider and receiver are the same user")
)
