// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: contracts/grpc/deals/v1/deals.proto

package dealspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DealsService_GetDealStatus_FullMethodName = "/barterport.deals.v1.DealsService/GetDealStatus"
)

// DealsServiceClient is the client API for DealsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DealsServiceClient interface {
	GetDealStatus(ctx context.Context, in *GetDealStatusRequest, opts ...grpc.CallOption) (*GetDealStatusResponse, error)
}

type dealsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDealsServiceClient(cc grpc.ClientConnInterface) DealsServiceClient {
	return &dealsServiceClient{cc}
}

func (c *dealsServiceClient) GetDealStatus(ctx context.Context, in *GetDealStatusRequest, opts ...grpc.CallOption) (*GetDealStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDealStatusResponse)
	err := c.cc.Invoke(ctx, DealsService_GetDealStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DealsServiceServer is the server API for DealsService service.
// All implementations must embed UnimplementedDealsServiceServer
// for forward compatibility.
type DealsServiceServer interface {
	GetDealStatus(context.Context, *GetDealStatusRequest) (*GetDealStatusResponse, error)
	mustEmbedUnimplementedDealsServiceServer()
}

// UnimplementedDealsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDealsServiceServer struct{}

func (UnimplementedDealsServiceServer) GetDealStatus(context.Context, *GetDealStatusRequest) (*GetDealStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDealStatus not implemented")
}
func (UnimplementedDealsServiceServer) mustEmbedUnimplementedDealsServiceServer() {}
func (UnimplementedDealsServiceServer) testEmbeddedByValue()                      {}

// UnsafeDealsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DealsServiceServer will
// result in compilation errors.
type UnsafeDealsServiceServer interface {
	mustEmbedUnimplementedDealsServiceServer()
}

func RegisterDealsServiceServer(s grpc.ServiceRegistrar, srv DealsServiceServer) {
	// If the following call panics, it indicates UnimplementedDealsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DealsService_ServiceDesc, srv)
}

func _DealsService_GetDealStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDealStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealsServiceServer).GetDealStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DealsService_GetDealStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealsServiceServer).GetDealStatus(ctx, req.(*GetDealStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DealsService_ServiceDesc is the grpc.ServiceDesc for DealsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DealsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "barterport.deals.v1.DealsService",
	HandlerType: (*DealsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDealStatus",
			Handler:    _DealsService_GetDealStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts/grpc/deals/v1/deals.proto",
}
