// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: contracts/grpc/deals/v1/deals.proto

package dealspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDealStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DealId        string                 `protobuf:"bytes,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDealStatusRequest) Reset() {
	*x = GetDealStatusRequest{}
	mi := &file_contracts_grpc_deals_v1_deals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDealStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDealStatusRequest) ProtoMessage() {}

func (x *GetDealStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_deals_v1_deals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDealStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDealStatusRequest) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_deals_v1_deals_proto_rawDescGZIP(), []int{0}
}

func (x *GetDealStatusRequest) GetDealId() string {
	if x != nil {
		return x.DealId
	}
	return ""
}

type GetDealStatusResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Status                  string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	HasPendingFailureReview bool                   `protobuf:"varint,2,opt,name=has_pending_failure_review,json=hasPendingFailureReview,proto3" json:"has_pending_failure_review,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetDealStatusResponse) Reset() {
	*x = GetDealStatusResponse{}
	mi := &file_contracts_grpc_deals_v1_deals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDealStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDealStatusResponse) ProtoMessage() {}

func (x *GetDealStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_deals_v1_deals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDealStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDealStatusResponse) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_deals_v1_deals_proto_rawDescGZIP(), []int{1}
}

func (x *GetDealStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDealStatusResponse) GetHasPendingFailureReview() bool {
	if x != nil {
		return x.HasPendingFailureReview
	}
	return false
}

var File_contracts_grpc_deals_v1_deals_proto protoreflect.FileDescriptor

const file_contracts_grpc_deals_v1_deals_proto_rawDesc = "" +
	"\n" +
	"#contracts/grpc/deals/v1/deals.proto\x12\x13barterport.deals.v1\"/\n" +
	"\x14GetDealStatusRequest\x12\x17\n" +
	"\adeal_id\x18\x01 \x01(\tR\x06dealId\"l\n" +
	"\x15GetDealStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12;\n" +
	"\x1ahas_pending_failure_review\x18\x02 \x01(\bR\x17hasPendingFailureReview2v\n" +
	"\fDealsService\x12f\n" +
	"\rGetDealStatus\x12).barterport.deals.v1.GetDealStatusRequest\x1a*.barterport.deals.v1.GetDealStatusResponseB5Z3barterport/internal/contracts/grpc/deals/v1;dealspbb\x06proto3"

var (
	file_contracts_grpc_deals_v1_deals_proto_rawDescOnce sync.Once
	file_contracts_grpc_deals_v1_deals_proto_rawDescData []byte
)

func file_contracts_grpc_deals_v1_deals_proto_rawDescGZIP() []byte {
	file_contracts_grpc_deals_v1_deals_proto_rawDescOnce.Do(func() {
		file_contracts_grpc_deals_v1_deals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_grpc_deals_v1_deals_proto_rawDesc), len(file_contracts_grpc_deals_v1_deals_proto_rawDesc)))
	})
	return file_contracts_grpc_deals_v1_deals_proto_rawDescData
}

var file_contracts_grpc_deals_v1_deals_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contracts_grpc_deals_v1_deals_proto_goTypes = []any{
	(*GetDealStatusRequest)(nil),  // 0: barterport.deals.v1.GetDealStatusRequest
	(*GetDealStatusResponse)(nil), // 1: barterport.deals.v1.GetDealStatusResponse
}
var file_contracts_grpc_deals_v1_deals_proto_depIdxs = []int32{
	0, // 0: barterport.deals.v1.DealsService.GetDealStatus:input_type -> barterport.deals.v1.GetDealStatusRequest
	1, // 1: barterport.deals.v1.DealsService.GetDealStatus:output_type -> barterport.deals.v1.GetDealStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_grpc_deals_v1_deals_proto_init() }
func file_contracts_grpc_deals_v1_deals_proto_init() {
	if File_contracts_grpc_deals_v1_deals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_grpc_deals_v1_deals_proto_rawDesc), len(file_contracts_grpc_deals_v1_deals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_grpc_deals_v1_deals_proto_goTypes,
		DependencyIndexes: file_contracts_grpc_deals_v1_deals_proto_depIdxs,
		MessageInfos:      file_contracts_grpc_deals_v1_deals_proto_msgTypes,
	}.Build()
	File_contracts_grpc_deals_v1_deals_proto = out.File
	file_contracts_grpc_deals_v1_deals_proto_goTypes = nil
	file_contracts_grpc_deals_v1_deals_proto_depIdxs = nil
}
