db:
  user: "postgres"
  host: "localhost"
  port: 5432
  name: "postgres"

jwt:
  access_ttl: 10m
  refresh_ttl: 90m

kafka:
  brokers:
    - "localhost:9094"
  user_creation_topic: "auth-users.user-created"
  user_creation_group: "users-service-uc"
  user_creation_result_topic: "users-auth.uc-results"
  user_creation_result_group: "auth-service-ucr"
  offer_report_penalty_topic: "deals-users.offer-report-penalty"
  offer_report_penalty_group: "users-service-orp"
  reputation_topic: "deals-users.reputation"
  reputation_group: "users-service-reputation"
  batch_size: 100
  poll_interval: 2s
  write_timeout: 10s

reputation:
  deal_completion_reward_points: 5
  review_creation_reward_points: 2

frontend:
  url: "http://localhost:5173"

mailer:
  host: "localhost"
  port: 2525
  user: "user"
  password: "password"
  from: "no-reply@local.test"
  tls_mode: "starttls"
  insecure_skip_verify: true
  bypass: false

admin:
  email: "admin@barterport.com"
  password: "admin123"

storage:
  endpoint: "http://localhost:8333"
  public_base_url: "http://localhost/s3"
  avatar_bucket: "avatars"
  offer_photo_bucket: "offer-photos"
  access_key_id: "barter-port-s3"
  secret_access_key: "barter-port-s3-secret"
  region: "us-east-1"

auth_grpc_addr: "localhost:50051"
auth_grpc_listen_addr: ":50051"
users_grpc_addr: "localhost:50052"
users_grpc_listen_addr: ":50052"
deals_grpc_addr: "localhost:50054"
deals_grpc_listen_addr: ":50054"
chats_grpc_addr: "localhost:50053"
chats_grpc_listen_addr: ":50053"
