db:
  user: "postgres"
  host: "localhost"
  port: 5432
  name: "postgres"

jwt:
  access_ttl: 10m
  refresh_ttl: 90m

kafka:
  brokers:
    - "localhost:9094"
  user_creation_topic: "auth-users.user-created"
  user_creation_group: "users-service-uc"
  user_creation_result_topic: "users-auth.uc-results"
  user_creation_result_group: "auth-service-ucr"
  batch_size: 100
  poll_interval: 2s
  write_timeout: 10s

frontend:
  url: "http://localhost:5173"

mailer:
  host: "localhost"
  port: 2525
  user: "user"
  password: "password"
  from: "no-reply@local.test"
  tls_mode: "starttls"
  insecure_skip_verify: true
  bypass: true

auth_grpc_addr: "localhost:50051"
auth_grpc_listen_addr: ":50051"
users_grpc_addr: "localhost:50052"
users_grpc_listen_addr: ":50052"