db:
  host: "db"

kafka:
  brokers:
    - "kafka:9092"

mailer:
  host: "smtp.yandex.ru"
  port: 465
  user: ""
  password: ""
  from: ""
  tls_mode: "tls"
  insecure_skip_verify: false

storage:
  endpoint: "http://seaweedfs:8333"
  filer_endpoint: "http://seaweedfs:8888"
  public_base_url: "http://localhost/s3"

auth_grpc_addr: "auth:50051"
auth_grpc_listen_addr: ":50051"
deals_grpc_addr: "deals:50054"
deals_grpc_listen_addr: ":50054"
users_grpc_addr: "users:50051"
users_grpc_listen_addr: ":50051"
chats_grpc_addr: "chats:50053"
chats_grpc_listen_addr: ":50053"
