services:
  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    restart: unless-stopped
    ports:
      - "5005:80"   # Web UI
      - "2525:25"   # SMTP
    environment:
      - ServerOptions__HostName=localhost
      - ServerOptions__AuthenticationRequired=true
      - ServerOptions__Users__0__Username=user
      - ServerOptions__Users__0__Password=password

  db:
    image: postgres:16
    container_name: barter-port-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql