// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: contracts/grpc/users/v1/users.proto

package userspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetUsersWithInfo
type GetUsersWithInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersWithInfoRequest) Reset() {
	*x = GetUsersWithInfoRequest{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersWithInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersWithInfoRequest) ProtoMessage() {}

func (x *GetUsersWithInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersWithInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUsersWithInfoRequest) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsersWithInfoRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUsersWithInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersWithInfoResponse) Reset() {
	*x = GetUsersWithInfoResponse{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersWithInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersWithInfoResponse) ProtoMessage() {}

func (x *GetUsersWithInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersWithInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUsersWithInfoResponse) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersWithInfoResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_contracts_grpc_users_v1_users_proto protoreflect.FileDescriptor

const file_contracts_grpc_users_v1_users_proto_rawDesc = "" +
	"\n" +
	"#contracts/grpc/users/v1/users.proto\x12\x13barterport.users.v1\"+\n" +
	"\x17GetUsersWithInfoRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\".\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"O\n" +
	"\x18GetUsersWithInfoResponse\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.barterport.users.v1.UserInfoR\x05users2\x7f\n" +
	"\fUsersService\x12o\n" +
	"\x10GetUsersWithInfo\x12,.barterport.users.v1.GetUsersWithInfoRequest\x1a-.barterport.users.v1.GetUsersWithInfoResponseB5Z3barterport/internal/contracts/grpc/users/v1;userspbb\x06proto3"

var (
	file_contracts_grpc_users_v1_users_proto_rawDescOnce sync.Once
	file_contracts_grpc_users_v1_users_proto_rawDescData []byte
)

func file_contracts_grpc_users_v1_users_proto_rawDescGZIP() []byte {
	file_contracts_grpc_users_v1_users_proto_rawDescOnce.Do(func() {
		file_contracts_grpc_users_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_grpc_users_v1_users_proto_rawDesc), len(file_contracts_grpc_users_v1_users_proto_rawDesc)))
	})
	return file_contracts_grpc_users_v1_users_proto_rawDescData
}

var file_contracts_grpc_users_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_contracts_grpc_users_v1_users_proto_goTypes = []any{
	(*GetUsersWithInfoRequest)(nil),  // 0: barterport.users.v1.GetUsersWithInfoRequest
	(*UserInfo)(nil),                 // 1: barterport.users.v1.UserInfo
	(*GetUsersWithInfoResponse)(nil), // 2: barterport.users.v1.GetUsersWithInfoResponse
}
var file_contracts_grpc_users_v1_users_proto_depIdxs = []int32{
	1, // 0: barterport.users.v1.GetUsersWithInfoResponse.users:type_name -> barterport.users.v1.UserInfo
	0, // 1: barterport.users.v1.UsersService.GetUsersWithInfo:input_type -> barterport.users.v1.GetUsersWithInfoRequest
	2, // 2: barterport.users.v1.UsersService.GetUsersWithInfo:output_type -> barterport.users.v1.GetUsersWithInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contracts_grpc_users_v1_users_proto_init() }
func file_contracts_grpc_users_v1_users_proto_init() {
	if File_contracts_grpc_users_v1_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_grpc_users_v1_users_proto_rawDesc), len(file_contracts_grpc_users_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_grpc_users_v1_users_proto_goTypes,
		DependencyIndexes: file_contracts_grpc_users_v1_users_proto_depIdxs,
		MessageInfos:      file_contracts_grpc_users_v1_users_proto_msgTypes,
	}.Build()
	File_contracts_grpc_users_v1_users_proto = out.File
	file_contracts_grpc_users_v1_users_proto_goTypes = nil
	file_contracts_grpc_users_v1_users_proto_depIdxs = nil
}
