// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: contracts/grpc/users/v1/users.proto

package userspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetUsersWithInfo
type GetUsersWithInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersWithInfoRequest) Reset() {
	*x = GetUsersWithInfoRequest{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersWithInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersWithInfoRequest) ProtoMessage() {}

func (x *GetUsersWithInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersWithInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUsersWithInfoRequest) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsersWithInfoRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUsersWithInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersWithInfoResponse) Reset() {
	*x = GetUsersWithInfoResponse{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersWithInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersWithInfoResponse) ProtoMessage() {}

func (x *GetUsersWithInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersWithInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUsersWithInfoResponse) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersWithInfoResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

// ListUsers
type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{3}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

// ListUsersForChatCreation
type ListUsersForChatCreationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequesterUserId string                 `protobuf:"bytes,1,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListUsersForChatCreationRequest) Reset() {
	*x = ListUsersForChatCreationRequest{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersForChatCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersForChatCreationRequest) ProtoMessage() {}

func (x *ListUsersForChatCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersForChatCreationRequest.ProtoReflect.Descriptor instead.
func (*ListUsersForChatCreationRequest) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersForChatCreationRequest) GetRequesterUserId() string {
	if x != nil {
		return x.RequesterUserId
	}
	return ""
}

type ListUsersForChatCreationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersForChatCreationResponse) Reset() {
	*x = ListUsersForChatCreationResponse{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersForChatCreationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersForChatCreationResponse) ProtoMessage() {}

func (x *ListUsersForChatCreationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersForChatCreationResponse.ProtoReflect.Descriptor instead.
func (*ListUsersForChatCreationResponse) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersForChatCreationResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

// Check for bidirectional subscription
type CheckSubscriptionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequesterUserId string                 `protobuf:"bytes,1,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`
	TargetUserId    string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckSubscriptionRequest) Reset() {
	*x = CheckSubscriptionRequest{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSubscriptionRequest) ProtoMessage() {}

func (x *CheckSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CheckSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{7}
}

func (x *CheckSubscriptionRequest) GetRequesterUserId() string {
	if x != nil {
		return x.RequesterUserId
	}
	return ""
}

func (x *CheckSubscriptionRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type CheckSubscriptionResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IsSubscribed           bool                   `protobuf:"varint,1,opt,name=is_subscribed,json=isSubscribed,proto3" json:"is_subscribed,omitempty"`
	HasCreatedSubscription bool                   `protobuf:"varint,2,opt,name=has_created_subscription,json=hasCreatedSubscription,proto3" json:"has_created_subscription,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CheckSubscriptionResponse) Reset() {
	*x = CheckSubscriptionResponse{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSubscriptionResponse) ProtoMessage() {}

func (x *CheckSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CheckSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{8}
}

func (x *CheckSubscriptionResponse) GetIsSubscribed() bool {
	if x != nil {
		return x.IsSubscribed
	}
	return false
}

func (x *CheckSubscriptionResponse) GetHasCreatedSubscription() bool {
	if x != nil {
		return x.HasCreatedSubscription
	}
	return false
}

// ListSubscriptions
type ListSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{9}
}

func (x *ListSubscriptionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*UserInfo            `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{10}
}

func (x *ListSubscriptionsResponse) GetSubscriptions() []*UserInfo {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

// GetUserLocation
type GetUserLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLocationRequest) Reset() {
	*x = GetUserLocationRequest{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLocationRequest) ProtoMessage() {}

func (x *GetUserLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLocationRequest.ProtoReflect.Descriptor instead.
func (*GetUserLocationRequest) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserLocationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      *float64               `protobuf:"fixed64,1,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,2,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLocationResponse) Reset() {
	*x = GetUserLocationResponse{}
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLocationResponse) ProtoMessage() {}

func (x *GetUserLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_users_v1_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLocationResponse.ProtoReflect.Descriptor instead.
func (*GetUserLocationResponse) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_users_v1_users_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserLocationResponse) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *GetUserLocationResponse) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

var File_contracts_grpc_users_v1_users_proto protoreflect.FileDescriptor

const file_contracts_grpc_users_v1_users_proto_rawDesc = "" +
	"\n" +
	"#contracts/grpc/users/v1/users.proto\x12\x13barterport.users.v1\"+\n" +
	"\x17GetUsersWithInfoRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\".\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"O\n" +
	"\x18GetUsersWithInfoResponse\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.barterport.users.v1.UserInfoR\x05users\"\x12\n" +
	"\x10ListUsersRequest\"H\n" +
	"\x11ListUsersResponse\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.barterport.users.v1.UserInfoR\x05users\"M\n" +
	"\x1fListUsersForChatCreationRequest\x12*\n" +
	"\x11requester_user_id\x18\x01 \x01(\tR\x0frequesterUserId\"W\n" +
	" ListUsersForChatCreationResponse\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.barterport.users.v1.UserInfoR\x05users\"l\n" +
	"\x18CheckSubscriptionRequest\x12*\n" +
	"\x11requester_user_id\x18\x01 \x01(\tR\x0frequesterUserId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\"z\n" +
	"\x19CheckSubscriptionResponse\x12#\n" +
	"\ris_subscribed\x18\x01 \x01(\bR\fisSubscribed\x128\n" +
	"\x18has_created_subscription\x18\x02 \x01(\bR\x16hasCreatedSubscription\"3\n" +
	"\x18ListSubscriptionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"`\n" +
	"\x19ListSubscriptionsResponse\x12C\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1d.barterport.users.v1.UserInfoR\rsubscriptions\"1\n" +
	"\x16GetUserLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"x\n" +
	"\x17GetUserLocationResponse\x12\x1f\n" +
	"\blatitude\x18\x01 \x01(\x01H\x00R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\x02 \x01(\x01H\x01R\tlongitude\x88\x01\x01B\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitude2\xbb\x05\n" +
	"\fUsersService\x12o\n" +
	"\x10GetUsersWithInfo\x12,.barterport.users.v1.GetUsersWithInfoRequest\x1a-.barterport.users.v1.GetUsersWithInfoResponse\x12Z\n" +
	"\tListUsers\x12%.barterport.users.v1.ListUsersRequest\x1a&.barterport.users.v1.ListUsersResponse\x12\x87\x01\n" +
	"\x18ListUsersForChatCreation\x124.barterport.users.v1.ListUsersForChatCreationRequest\x1a5.barterport.users.v1.ListUsersForChatCreationResponse\x12r\n" +
	"\x11CheckSubscription\x12-.barterport.users.v1.CheckSubscriptionRequest\x1a..barterport.users.v1.CheckSubscriptionResponse\x12r\n" +
	"\x11ListSubscriptions\x12-.barterport.users.v1.ListSubscriptionsRequest\x1a..barterport.users.v1.ListSubscriptionsResponse\x12l\n" +
	"\x0fGetUserLocation\x12+.barterport.users.v1.GetUserLocationRequest\x1a,.barterport.users.v1.GetUserLocationResponseB5Z3barterport/internal/contracts/grpc/users/v1;userspbb\x06proto3"

var (
	file_contracts_grpc_users_v1_users_proto_rawDescOnce sync.Once
	file_contracts_grpc_users_v1_users_proto_rawDescData []byte
)

func file_contracts_grpc_users_v1_users_proto_rawDescGZIP() []byte {
	file_contracts_grpc_users_v1_users_proto_rawDescOnce.Do(func() {
		file_contracts_grpc_users_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_grpc_users_v1_users_proto_rawDesc), len(file_contracts_grpc_users_v1_users_proto_rawDesc)))
	})
	return file_contracts_grpc_users_v1_users_proto_rawDescData
}

var file_contracts_grpc_users_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_contracts_grpc_users_v1_users_proto_goTypes = []any{
	(*GetUsersWithInfoRequest)(nil),          // 0: barterport.users.v1.GetUsersWithInfoRequest
	(*UserInfo)(nil),                         // 1: barterport.users.v1.UserInfo
	(*GetUsersWithInfoResponse)(nil),         // 2: barterport.users.v1.GetUsersWithInfoResponse
	(*ListUsersRequest)(nil),                 // 3: barterport.users.v1.ListUsersRequest
	(*ListUsersResponse)(nil),                // 4: barterport.users.v1.ListUsersResponse
	(*ListUsersForChatCreationRequest)(nil),  // 5: barterport.users.v1.ListUsersForChatCreationRequest
	(*ListUsersForChatCreationResponse)(nil), // 6: barterport.users.v1.ListUsersForChatCreationResponse
	(*CheckSubscriptionRequest)(nil),         // 7: barterport.users.v1.CheckSubscriptionRequest
	(*CheckSubscriptionResponse)(nil),        // 8: barterport.users.v1.CheckSubscriptionResponse
	(*ListSubscriptionsRequest)(nil),         // 9: barterport.users.v1.ListSubscriptionsRequest
	(*ListSubscriptionsResponse)(nil),        // 10: barterport.users.v1.ListSubscriptionsResponse
	(*GetUserLocationRequest)(nil),           // 11: barterport.users.v1.GetUserLocationRequest
	(*GetUserLocationResponse)(nil),          // 12: barterport.users.v1.GetUserLocationResponse
}
var file_contracts_grpc_users_v1_users_proto_depIdxs = []int32{
	1,  // 0: barterport.users.v1.GetUsersWithInfoResponse.users:type_name -> barterport.users.v1.UserInfo
	1,  // 1: barterport.users.v1.ListUsersResponse.users:type_name -> barterport.users.v1.UserInfo
	1,  // 2: barterport.users.v1.ListUsersForChatCreationResponse.users:type_name -> barterport.users.v1.UserInfo
	1,  // 3: barterport.users.v1.ListSubscriptionsResponse.subscriptions:type_name -> barterport.users.v1.UserInfo
	0,  // 4: barterport.users.v1.UsersService.GetUsersWithInfo:input_type -> barterport.users.v1.GetUsersWithInfoRequest
	3,  // 5: barterport.users.v1.UsersService.ListUsers:input_type -> barterport.users.v1.ListUsersRequest
	5,  // 6: barterport.users.v1.UsersService.ListUsersForChatCreation:input_type -> barterport.users.v1.ListUsersForChatCreationRequest
	7,  // 7: barterport.users.v1.UsersService.CheckSubscription:input_type -> barterport.users.v1.CheckSubscriptionRequest
	9,  // 8: barterport.users.v1.UsersService.ListSubscriptions:input_type -> barterport.users.v1.ListSubscriptionsRequest
	11, // 9: barterport.users.v1.UsersService.GetUserLocation:input_type -> barterport.users.v1.GetUserLocationRequest
	2,  // 10: barterport.users.v1.UsersService.GetUsersWithInfo:output_type -> barterport.users.v1.GetUsersWithInfoResponse
	4,  // 11: barterport.users.v1.UsersService.ListUsers:output_type -> barterport.users.v1.ListUsersResponse
	6,  // 12: barterport.users.v1.UsersService.ListUsersForChatCreation:output_type -> barterport.users.v1.ListUsersForChatCreationResponse
	8,  // 13: barterport.users.v1.UsersService.CheckSubscription:output_type -> barterport.users.v1.CheckSubscriptionResponse
	10, // 14: barterport.users.v1.UsersService.ListSubscriptions:output_type -> barterport.users.v1.ListSubscriptionsResponse
	12, // 15: barterport.users.v1.UsersService.GetUserLocation:output_type -> barterport.users.v1.GetUserLocationResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_contracts_grpc_users_v1_users_proto_init() }
func file_contracts_grpc_users_v1_users_proto_init() {
	if File_contracts_grpc_users_v1_users_proto != nil {
		return
	}
	file_contracts_grpc_users_v1_users_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_grpc_users_v1_users_proto_rawDesc), len(file_contracts_grpc_users_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_grpc_users_v1_users_proto_goTypes,
		DependencyIndexes: file_contracts_grpc_users_v1_users_proto_depIdxs,
		MessageInfos:      file_contracts_grpc_users_v1_users_proto_msgTypes,
	}.Build()
	File_contracts_grpc_users_v1_users_proto = out.File
	file_contracts_grpc_users_v1_users_proto_goTypes = nil
	file_contracts_grpc_users_v1_users_proto_depIdxs = nil
}
