// Code generated by "enumer -type=Enum -json -text -sql"; DO NOT EDIT.

package status_update

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _EnumName = "SuccessFailed"

var _EnumIndex = [...]uint8{0, 7, 13}

const _EnumLowerName = "successfailed"

func (i Enum) String() string {
	if i < 0 || i >= Enum(len(_EnumIndex)-1) {
		return fmt.Sprintf("Enum(%d)", i)
	}
	return _EnumName[_EnumIndex[i]:_EnumIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EnumNoOp() {
	var x [1]struct{}
	_ = x[Success-(0)]
	_ = x[Failed-(1)]
}

var _EnumValues = []Enum{Success, Failed}

var _EnumNameToValueMap = map[string]Enum{
	_EnumName[0:7]:       Success,
	_EnumLowerName[0:7]:  Success,
	_EnumName[7:13]:      Failed,
	_EnumLowerName[7:13]: Failed,
}

var _EnumNames = []string{
	_EnumName[0:7],
	_EnumName[7:13],
}

// EnumString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EnumString(s string) (Enum, error) {
	if val, ok := _EnumNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EnumNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Enum values", s)
}

// EnumValues returns all values of the enum
func EnumValues() []Enum {
	return _EnumValues
}

// EnumStrings returns a slice of all String values of the enum
func EnumStrings() []string {
	strs := make([]string, len(_EnumNames))
	copy(strs, _EnumNames)
	return strs
}

// IsAEnum returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Enum) IsAEnum() bool {
	for _, v := range _EnumValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Enum
func (i Enum) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Enum
func (i *Enum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Enum should be a string, got %s", data)
	}

	var err error
	*i, err = EnumString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Enum
func (i Enum) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Enum
func (i *Enum) UnmarshalText(text []byte) error {
	var err error
	*i, err = EnumString(string(text))
	return err
}

func (i Enum) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Enum) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Enum: %[1]T(%[1]v)", value)
	}

	val, err := EnumString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
