// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: contracts/grpc/auth/v1/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetMe
type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_contracts_grpc_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetMeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_contracts_grpc_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetMeResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetMeResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetMeResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

var File_contracts_grpc_auth_v1_auth_proto protoreflect.FileDescriptor

const file_contracts_grpc_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"!contracts/grpc/auth/v1/auth.proto\x12\x13linktracker.auth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1e\n" +
	"\fGetMeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"{\n" +
	"\rGetMeResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin2]\n" +
	"\vAuthService\x12N\n" +
	"\x05GetMe\x12!.linktracker.auth.v1.GetMeRequest\x1a\".linktracker.auth.v1.GetMeResponseB5Z3link-tracker/internal/contracts/grpc/auth/v1;authpbb\x06proto3"

var (
	file_contracts_grpc_auth_v1_auth_proto_rawDescOnce sync.Once
	file_contracts_grpc_auth_v1_auth_proto_rawDescData []byte
)

func file_contracts_grpc_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_contracts_grpc_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_contracts_grpc_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_grpc_auth_v1_auth_proto_rawDesc), len(file_contracts_grpc_auth_v1_auth_proto_rawDesc)))
	})
	return file_contracts_grpc_auth_v1_auth_proto_rawDescData
}

var file_contracts_grpc_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contracts_grpc_auth_v1_auth_proto_goTypes = []any{
	(*GetMeRequest)(nil),          // 0: linktracker.auth.v1.GetMeRequest
	(*GetMeResponse)(nil),         // 1: linktracker.auth.v1.GetMeResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_contracts_grpc_auth_v1_auth_proto_depIdxs = []int32{
	2, // 0: linktracker.auth.v1.GetMeResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: linktracker.auth.v1.AuthService.GetMe:input_type -> linktracker.auth.v1.GetMeRequest
	1, // 2: linktracker.auth.v1.AuthService.GetMe:output_type -> linktracker.auth.v1.GetMeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contracts_grpc_auth_v1_auth_proto_init() }
func file_contracts_grpc_auth_v1_auth_proto_init() {
	if File_contracts_grpc_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_grpc_auth_v1_auth_proto_rawDesc), len(file_contracts_grpc_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_grpc_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_contracts_grpc_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_contracts_grpc_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_contracts_grpc_auth_v1_auth_proto = out.File
	file_contracts_grpc_auth_v1_auth_proto_goTypes = nil
	file_contracts_grpc_auth_v1_auth_proto_depIdxs = nil
}
