// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: contracts/grpc/auth/v1/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetMe
type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_contracts_grpc_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetMeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_contracts_grpc_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetMeResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetMeResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetMeResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

var File_contracts_grpc_auth_v1_auth_proto protoreflect.FileDescriptor

var file_contracts_grpc_auth_v1_auth_proto_rawDesc = []byte{
	10, 33, 99, 111, 110, 116, 114, 97, 99, 116, 115, 47, 103, 114, 112, 99, 47, 97, 117, 116, 104,
	47, 118, 49, 47, 97, 117, 116, 104, 46, 112, 114, 111, 116, 111, 18, 19, 108, 105, 110, 107,
	116, 114, 97, 99, 107, 101, 114, 46, 97, 117, 116, 104, 46, 118, 49, 26, 31, 103, 111, 111, 103,
	108, 101, 47, 112, 114, 111, 116, 111, 98, 117, 102, 47, 116, 105, 109, 101, 115, 116, 97, 109,
	112, 46, 112, 114, 111, 116, 111, 34, 30, 10, 12, 71, 101, 116, 77, 101, 82, 101, 113, 117, 101,
	115, 116, 18, 14, 10, 2, 105, 100, 24, 1, 32, 1, 40, 9, 82, 2, 105, 100, 34, 123, 10, 13, 71,
	101, 116, 77, 101, 82, 101, 115, 112, 111, 110, 115, 101, 18, 20, 10, 5, 101, 109, 97, 105, 108,
	24, 1, 32, 1, 40, 9, 82, 5, 101, 109, 97, 105, 108, 18, 57, 10, 10, 99, 114, 101, 97, 116, 101,
	100, 95, 97, 116, 24, 2, 32, 1, 40, 11, 50, 26, 46, 103, 111, 111, 103, 108, 101, 46, 112, 114,
	111, 116, 111, 98, 117, 102, 46, 84, 105, 109, 101, 115, 116, 97, 109, 112, 82, 9, 99, 114, 101,
	97, 116, 101, 100, 65, 116, 18, 25, 10, 8, 105, 115, 95, 97, 100, 109, 105, 110, 24, 3, 32, 1,
	40, 8, 82, 7, 105, 115, 65, 100, 109, 105, 110, 50, 93, 10, 11, 65, 117, 116, 104, 83, 101, 114,
	118, 105, 99, 101, 18, 78, 10, 5, 71, 101, 116, 77, 101, 18, 33, 46, 108, 105, 110, 107, 116,
	114, 97, 99, 107, 101, 114, 46, 97, 117, 116, 104, 46, 118, 49, 46, 71, 101, 116, 77, 101, 82,
	101, 113, 117, 101, 115, 116, 26, 34, 46, 108, 105, 110, 107, 116, 114, 97, 99, 107, 101, 114,
	46, 97, 117, 116, 104, 46, 118, 49, 46, 71, 101, 116, 77, 101, 82, 101, 115, 112, 111, 110, 115,
	101, 66, 53, 90, 51, 108, 105, 110, 107, 45, 116, 114, 97, 99, 107, 101, 114, 47, 105, 110, 116,
	101, 114, 110, 97, 108, 47, 99, 111, 110, 116, 114, 97, 99, 116, 115, 47, 103, 114, 112, 99, 47,
	97, 117, 116, 104, 47, 118, 49, 59, 97, 117, 116, 104, 112, 98, 98, 6, 112, 114, 111, 116, 111,
	51,
}

var (
	file_contracts_grpc_auth_v1_auth_proto_rawDescOnce sync.Once
	file_contracts_grpc_auth_v1_auth_proto_rawDescData []byte
)

func file_contracts_grpc_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_contracts_grpc_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_contracts_grpc_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_contracts_grpc_auth_v1_auth_proto_rawDesc)
	})
	return file_contracts_grpc_auth_v1_auth_proto_rawDescData
}

var file_contracts_grpc_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contracts_grpc_auth_v1_auth_proto_goTypes = []any{
	(*GetMeRequest)(nil),          // 0: linktracker.auth.v1.GetMeRequest
	(*GetMeResponse)(nil),         // 1: linktracker.auth.v1.GetMeResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_contracts_grpc_auth_v1_auth_proto_depIdxs = []int32{
	2, // 0: linktracker.auth.v1.GetMeResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: linktracker.auth.v1.AuthService.GetMe:input_type -> linktracker.auth.v1.GetMeRequest
	1, // 2: linktracker.auth.v1.AuthService.GetMe:output_type -> linktracker.auth.v1.GetMeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contracts_grpc_auth_v1_auth_proto_init() }
func file_contracts_grpc_auth_v1_auth_proto_init() {
	if File_contracts_grpc_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contracts_grpc_auth_v1_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_grpc_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_contracts_grpc_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_contracts_grpc_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_contracts_grpc_auth_v1_auth_proto = out.File
	file_contracts_grpc_auth_v1_auth_proto_goTypes = nil
	file_contracts_grpc_auth_v1_auth_proto_depIdxs = nil
}
