openapi: 3.0.3
info:
  title: Deals API
  description: Deals API
  version: 1.0.0

servers:
  - url: 'http://localhost:80'

paths:
  /deals/drafts:
    $ref: './paths/deals.yaml#/dealsDrafts'
  /deals/drafts/my:
    $ref: './paths/deals.yaml#/dealsDraftsMy'
  /deals/drafts/{draftId}:
    $ref: './paths/deals.yaml#/dealsDraftsById'
  /deals/drafts/{draftId}/cancel:
    $ref: './paths/deals.yaml#/dealsDraftsCancel'
  /offers:
    $ref: './paths/offers.yaml#/offers'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
