// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: contracts/grpc/chats/v1/chats.proto

package chatspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateChat
type CreateChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DealId         string                 `protobuf:"bytes,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"` // пустая строка для прямых чатов
	ParticipantIds []string               `protobuf:"bytes,2,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_contracts_grpc_chats_v1_chats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_chats_v1_chats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_chats_v1_chats_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatRequest) GetDealId() string {
	if x != nil {
		return x.DealId
	}
	return ""
}

func (x *CreateChatRequest) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

type CreateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatResponse) Reset() {
	*x = CreateChatResponse{}
	mi := &file_contracts_grpc_chats_v1_chats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatResponse) ProtoMessage() {}

func (x *CreateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_grpc_chats_v1_chats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatResponse.ProtoReflect.Descriptor instead.
func (*CreateChatResponse) Descriptor() ([]byte, []int) {
	return file_contracts_grpc_chats_v1_chats_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChatResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

var File_contracts_grpc_chats_v1_chats_proto protoreflect.FileDescriptor

const file_contracts_grpc_chats_v1_chats_proto_rawDesc = "" +
	"\n" +
	"#contracts/grpc/chats/v1/chats.proto\x12\x13barterport.chats.v1\"U\n" +
	"\x11CreateChatRequest\x12\x17\n" +
	"\adeal_id\x18\x01 \x01(\tR\x06dealId\x12'\n" +
	"\x0fparticipant_ids\x18\x02 \x03(\tR\x0eparticipantIds\"-\n" +
	"\x12CreateChatResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId2m\n" +
	"\fChatsService\x12]\n" +
	"\n" +
	"CreateChat\x12&.barterport.chats.v1.CreateChatRequest\x1a'.barterport.chats.v1.CreateChatResponseB5Z3barterport/internal/contracts/grpc/chats/v1;chatspbb\x06proto3"

var (
	file_contracts_grpc_chats_v1_chats_proto_rawDescOnce sync.Once
	file_contracts_grpc_chats_v1_chats_proto_rawDescData []byte
)

func file_contracts_grpc_chats_v1_chats_proto_rawDescGZIP() []byte {
	file_contracts_grpc_chats_v1_chats_proto_rawDescOnce.Do(func() {
		file_contracts_grpc_chats_v1_chats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_grpc_chats_v1_chats_proto_rawDesc), len(file_contracts_grpc_chats_v1_chats_proto_rawDesc)))
	})
	return file_contracts_grpc_chats_v1_chats_proto_rawDescData
}

var file_contracts_grpc_chats_v1_chats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contracts_grpc_chats_v1_chats_proto_goTypes = []any{
	(*CreateChatRequest)(nil),  // 0: barterport.chats.v1.CreateChatRequest
	(*CreateChatResponse)(nil), // 1: barterport.chats.v1.CreateChatResponse
}
var file_contracts_grpc_chats_v1_chats_proto_depIdxs = []int32{
	0, // 0: barterport.chats.v1.ChatsService.CreateChat:input_type -> barterport.chats.v1.CreateChatRequest
	1, // 1: barterport.chats.v1.ChatsService.CreateChat:output_type -> barterport.chats.v1.CreateChatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_grpc_chats_v1_chats_proto_init() }
func file_contracts_grpc_chats_v1_chats_proto_init() {
	if File_contracts_grpc_chats_v1_chats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_grpc_chats_v1_chats_proto_rawDesc), len(file_contracts_grpc_chats_v1_chats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_grpc_chats_v1_chats_proto_goTypes,
		DependencyIndexes: file_contracts_grpc_chats_v1_chats_proto_depIdxs,
		MessageInfos:      file_contracts_grpc_chats_v1_chats_proto_msgTypes,
	}.Build()
	File_contracts_grpc_chats_v1_chats_proto = out.File
	file_contracts_grpc_chats_v1_chats_proto_goTypes = nil
	file_contracts_grpc_chats_v1_chats_proto_depIdxs = nil
}
