// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: contracts/grpc/chats/v1/chats.proto

package chatspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatsService_CreateChat_FullMethodName    = "/barterport.chats.v1.ChatsService/CreateChat"
	ChatsService_GetDealChatId_FullMethodName = "/barterport.chats.v1.ChatsService/GetDealChatId"
)

// ChatsServiceClient is the client API for ChatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatsServiceClient interface {
	CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*CreateChatResponse, error)
	GetDealChatId(ctx context.Context, in *GetDealChatIdRequest, opts ...grpc.CallOption) (*GetDealChatIdResponse, error)
}

type chatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatsServiceClient(cc grpc.ClientConnInterface) ChatsServiceClient {
	return &chatsServiceClient{cc}
}

func (c *chatsServiceClient) CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*CreateChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChatResponse)
	err := c.cc.Invoke(ctx, ChatsService_CreateChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatsServiceClient) GetDealChatId(ctx context.Context, in *GetDealChatIdRequest, opts ...grpc.CallOption) (*GetDealChatIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDealChatIdResponse)
	err := c.cc.Invoke(ctx, ChatsService_GetDealChatId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatsServiceServer is the server API for ChatsService service.
// All implementations must embed UnimplementedChatsServiceServer
// for forward compatibility.
type ChatsServiceServer interface {
	CreateChat(context.Context, *CreateChatRequest) (*CreateChatResponse, error)
	GetDealChatId(context.Context, *GetDealChatIdRequest) (*GetDealChatIdResponse, error)
	mustEmbedUnimplementedChatsServiceServer()
}

// UnimplementedChatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatsServiceServer struct{}

func (UnimplementedChatsServiceServer) CreateChat(context.Context, *CreateChatRequest) (*CreateChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChat not implemented")
}
func (UnimplementedChatsServiceServer) GetDealChatId(context.Context, *GetDealChatIdRequest) (*GetDealChatIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDealChatId not implemented")
}
func (UnimplementedChatsServiceServer) mustEmbedUnimplementedChatsServiceServer() {}
func (UnimplementedChatsServiceServer) testEmbeddedByValue()                      {}

// UnsafeChatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatsServiceServer will
// result in compilation errors.
type UnsafeChatsServiceServer interface {
	mustEmbedUnimplementedChatsServiceServer()
}

func RegisterChatsServiceServer(s grpc.ServiceRegistrar, srv ChatsServiceServer) {
	// If the following call panics, it indicates UnimplementedChatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatsService_ServiceDesc, srv)
}

func _ChatsService_CreateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatsServiceServer).CreateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatsService_CreateChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatsServiceServer).CreateChat(ctx, req.(*CreateChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatsService_GetDealChatId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDealChatIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatsServiceServer).GetDealChatId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatsService_GetDealChatId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatsServiceServer).GetDealChatId(ctx, req.(*GetDealChatIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatsService_ServiceDesc is the grpc.ServiceDesc for ChatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "barterport.chats.v1.ChatsService",
	HandlerType: (*ChatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChat",
			Handler:    _ChatsService_CreateChat_Handler,
		},
		{
			MethodName: "GetDealChatId",
			Handler:    _ChatsService_GetDealChatId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts/grpc/chats/v1/chats.proto",
}
