SortType:
  name: sort
  in: query
  required: true
  description: Режим сортировки списка объявлений
  schema:
    type: string
    enum:
      - ByTime
      - ByPopularity

CursorCreatedAt:
  name: cursor_created_at
  in: query
  required: false
  description: |
    Временная метка создания курсора в формате RFC3339.
    Используется вместе с `cursor_id`, когда `sort=created_at`.
  schema:
    type: string
    format: date-time

CursorViews:
  name: cursor_views
  in: query
  required: false
  description: |
    Количество просмотров в курсоре.
    Используется вместе с `cursor_id`, когда `sort=popularity`.
  schema:
    type: integer
    format: int64
    minimum: 0

CursorId:
  name: cursor_id
  in: query
  required: false
  description: |
    ID объявления в курсоре, используемый как дополнительный критерий для стабильной пагинации.
  schema:
    type: string
    format: uuid

Limit:
  name: cursor_limit
  in: query
  required: false
  description: Максимальное количество объявлений в ответе
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 10