// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Chat defines model for Chat.
type Chat struct {
	// CreatedAt Chat creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// DealId Deal ID if the chat is attached to a deal; null for direct chats
	DealId *openapi_types.UUID `json:"deal_id,omitempty"`

	// Id Unique chat identifier
	Id openapi_types.UUID `json:"id"`

	// Participants Chat participant IDs
	Participants []Participant `json:"participants"`
}

// CreateChatRequest defines model for CreateChatRequest.
type CreateChatRequest struct {
	// ParticipantId User ID of the second participant for a direct chat
	ParticipantId openapi_types.UUID `json:"participant_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// GetMessagesResponse defines model for GetMessagesResponse.
type GetMessagesResponse = []Message

// ListChatsResponse defines model for ListChatsResponse.
type ListChatsResponse = []Chat

// ListUsersResponse defines model for ListUsersResponse.
type ListUsersResponse = []User

// Message defines model for Message.
type Message struct {
	// ChatId Chat ID
	ChatId openapi_types.UUID `json:"chat_id"`

	// Content Message text
	Content string `json:"content"`

	// CreatedAt Message creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Id Unique message identifier
	Id openapi_types.UUID `json:"id"`

	// SenderId Sender user ID
	SenderId openapi_types.UUID `json:"sender_id"`
}

// Participant defines model for Participant.
type Participant struct {
	// UserId User ID of the participant
	UserId openapi_types.UUID `json:"user_id"`

	// UserName User display name
	UserName *string `json:"user_name,omitempty"`
}

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	// Content Message text
	Content string `json:"content"`
}

// User defines model for User.
type User struct {
	// Id User ID
	Id openapi_types.UUID `json:"id"`

	// Name User display name
	Name string `json:"name"`
}

// After defines model for After.
type After = time.Time

// ChatId defines model for ChatId.
type ChatId = openapi_types.UUID

// GetChatMessagesParams defines parameters for GetChatMessages.
type GetChatMessagesParams struct {
	// After Return only messages created after the specified timestamp.
	// The value must be in RFC3339 / RFC3339Nano format.
	After *After `form:"after,omitempty" json:"after,omitempty"`
}

// CreateChatJSONRequestBody defines body for CreateChat for application/json ContentType.
type CreateChatJSONRequestBody = CreateChatRequest

// SendChatMessageJSONRequestBody defines body for SendChatMessage for application/json ContentType.
type SendChatMessageJSONRequestBody = SendMessageRequest
