// Code generated by "enumer -type=DealStatus -json -text -sql -trimprefix=DealStatus"; DO NOT EDIT.

package enums

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _DealStatusName = "LookingForParticipantsDiscussionConfirmedCompletedCancelledFailed"

var _DealStatusIndex = [...]uint8{0, 22, 32, 41, 50, 59, 65}

const _DealStatusLowerName = "lookingforparticipantsdiscussionconfirmedcompletedcancelledfailed"

func (i DealStatus) String() string {
	if i < 0 || i >= DealStatus(len(_DealStatusIndex)-1) {
		return fmt.Sprintf("DealStatus(%d)", i)
	}
	return _DealStatusName[_DealStatusIndex[i]:_DealStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DealStatusNoOp() {
	var x [1]struct{}
	_ = x[DealStatusLookingForParticipants-(0)]
	_ = x[DealStatusDiscussion-(1)]
	_ = x[DealStatusConfirmed-(2)]
	_ = x[DealStatusCompleted-(3)]
	_ = x[DealStatusCancelled-(4)]
	_ = x[DealStatusFailed-(5)]
}

var _DealStatusValues = []DealStatus{DealStatusLookingForParticipants, DealStatusDiscussion, DealStatusConfirmed, DealStatusCompleted, DealStatusCancelled, DealStatusFailed}

var _DealStatusNameToValueMap = map[string]DealStatus{
	_DealStatusName[0:22]:       DealStatusLookingForParticipants,
	_DealStatusLowerName[0:22]:  DealStatusLookingForParticipants,
	_DealStatusName[22:32]:      DealStatusDiscussion,
	_DealStatusLowerName[22:32]: DealStatusDiscussion,
	_DealStatusName[32:41]:      DealStatusConfirmed,
	_DealStatusLowerName[32:41]: DealStatusConfirmed,
	_DealStatusName[41:50]:      DealStatusCompleted,
	_DealStatusLowerName[41:50]: DealStatusCompleted,
	_DealStatusName[50:59]:      DealStatusCancelled,
	_DealStatusLowerName[50:59]: DealStatusCancelled,
	_DealStatusName[59:65]:      DealStatusFailed,
	_DealStatusLowerName[59:65]: DealStatusFailed,
}

var _DealStatusNames = []string{
	_DealStatusName[0:22],
	_DealStatusName[22:32],
	_DealStatusName[32:41],
	_DealStatusName[41:50],
	_DealStatusName[50:59],
	_DealStatusName[59:65],
}

// DealStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DealStatusString(s string) (DealStatus, error) {
	if val, ok := _DealStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DealStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DealStatus values", s)
}

// DealStatusValues returns all values of the enum
func DealStatusValues() []DealStatus {
	return _DealStatusValues
}

// DealStatusStrings returns a slice of all String values of the enum
func DealStatusStrings() []string {
	strs := make([]string, len(_DealStatusNames))
	copy(strs, _DealStatusNames)
	return strs
}

// IsADealStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DealStatus) IsADealStatus() bool {
	for _, v := range _DealStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DealStatus
func (i DealStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DealStatus
func (i *DealStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DealStatus should be a string, got %s", data)
	}

	var err error
	*i, err = DealStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for DealStatus
func (i DealStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for DealStatus
func (i *DealStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = DealStatusString(string(text))
	return err
}

func (i DealStatus) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *DealStatus) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of DealStatus: %[1]T(%[1]v)", value)
	}

	val, err := DealStatusString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
