// Code generated by "enumer -type=ItemType -json -text -sql -transform=lower"; DO NOT EDIT.

package enums

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _ItemTypeName = "itemtypegooditemtypeservice"

var _ItemTypeIndex = [...]uint8{0, 12, 27}

const _ItemTypeLowerName = "itemtypegooditemtypeservice"

func (i ItemType) String() string {
	if i < 0 || i >= ItemType(len(_ItemTypeIndex)-1) {
		return fmt.Sprintf("ItemType(%d)", i)
	}
	return _ItemTypeName[_ItemTypeIndex[i]:_ItemTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ItemTypeNoOp() {
	var x [1]struct{}
	_ = x[ItemTypeGood-(0)]
	_ = x[ItemTypeService-(1)]
}

var _ItemTypeValues = []ItemType{ItemTypeGood, ItemTypeService}

var _ItemTypeNameToValueMap = map[string]ItemType{
	_ItemTypeName[0:12]:       ItemTypeGood,
	_ItemTypeLowerName[0:12]:  ItemTypeGood,
	_ItemTypeName[12:27]:      ItemTypeService,
	_ItemTypeLowerName[12:27]: ItemTypeService,
}

var _ItemTypeNames = []string{
	_ItemTypeName[0:12],
	_ItemTypeName[12:27],
}

// ItemTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ItemTypeString(s string) (ItemType, error) {
	if val, ok := _ItemTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ItemTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ItemType values", s)
}

// ItemTypeValues returns all values of the enum
func ItemTypeValues() []ItemType {
	return _ItemTypeValues
}

// ItemTypeStrings returns a slice of all String values of the enum
func ItemTypeStrings() []string {
	strs := make([]string, len(_ItemTypeNames))
	copy(strs, _ItemTypeNames)
	return strs
}

// IsAItemType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ItemType) IsAItemType() bool {
	for _, v := range _ItemTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ItemType
func (i ItemType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ItemType
func (i *ItemType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ItemType should be a string, got %s", data)
	}

	var err error
	*i, err = ItemTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ItemType
func (i ItemType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ItemType
func (i *ItemType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ItemTypeString(string(text))
	return err
}

func (i ItemType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *ItemType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of ItemType: %[1]T(%[1]v)", value)
	}

	val, err := ItemTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
