// Code generated by "enumer -type=OfferAction -json -text -sql -transform=lower"; DO NOT EDIT.

package enums

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _OfferActionName = "offeractiongiveofferactiontake"

var _OfferActionIndex = [...]uint8{0, 15, 30}

const _OfferActionLowerName = "offeractiongiveofferactiontake"

func (i OfferAction) String() string {
	if i < 0 || i >= OfferAction(len(_OfferActionIndex)-1) {
		return fmt.Sprintf("OfferAction(%d)", i)
	}
	return _OfferActionName[_OfferActionIndex[i]:_OfferActionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OfferActionNoOp() {
	var x [1]struct{}
	_ = x[OfferActionGive-(0)]
	_ = x[OfferActionTake-(1)]
}

var _OfferActionValues = []OfferAction{OfferActionGive, OfferActionTake}

var _OfferActionNameToValueMap = map[string]OfferAction{
	_OfferActionName[0:15]:       OfferActionGive,
	_OfferActionLowerName[0:15]:  OfferActionGive,
	_OfferActionName[15:30]:      OfferActionTake,
	_OfferActionLowerName[15:30]: OfferActionTake,
}

var _OfferActionNames = []string{
	_OfferActionName[0:15],
	_OfferActionName[15:30],
}

// OfferActionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OfferActionString(s string) (OfferAction, error) {
	if val, ok := _OfferActionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OfferActionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OfferAction values", s)
}

// OfferActionValues returns all values of the enum
func OfferActionValues() []OfferAction {
	return _OfferActionValues
}

// OfferActionStrings returns a slice of all String values of the enum
func OfferActionStrings() []string {
	strs := make([]string, len(_OfferActionNames))
	copy(strs, _OfferActionNames)
	return strs
}

// IsAOfferAction returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OfferAction) IsAOfferAction() bool {
	for _, v := range _OfferActionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for OfferAction
func (i OfferAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for OfferAction
func (i *OfferAction) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("OfferAction should be a string, got %s", data)
	}

	var err error
	*i, err = OfferActionString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for OfferAction
func (i OfferAction) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for OfferAction
func (i *OfferAction) UnmarshalText(text []byte) error {
	var err error
	*i, err = OfferActionString(string(text))
	return err
}

func (i OfferAction) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *OfferAction) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of OfferAction: %[1]T(%[1]v)", value)
	}

	val, err := OfferActionString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
