// Code generated by "enumer -type=SortType -json -text -sql"; DO NOT EDIT.

package enums

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _SortTypeName = "SortTypeByTimeSortTypeByPopularity"

var _SortTypeIndex = [...]uint8{0, 14, 34}

const _SortTypeLowerName = "sorttypebytimesorttypebypopularity"

func (i SortType) String() string {
	if i < 0 || i >= SortType(len(_SortTypeIndex)-1) {
		return fmt.Sprintf("SortType(%d)", i)
	}
	return _SortTypeName[_SortTypeIndex[i]:_SortTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SortTypeNoOp() {
	var x [1]struct{}
	_ = x[SortTypeByTime-(0)]
	_ = x[SortTypeByPopularity-(1)]
}

var _SortTypeValues = []SortType{SortTypeByTime, SortTypeByPopularity}

var _SortTypeNameToValueMap = map[string]SortType{
	_SortTypeName[0:14]:       SortTypeByTime,
	_SortTypeLowerName[0:14]:  SortTypeByTime,
	_SortTypeName[14:34]:      SortTypeByPopularity,
	_SortTypeLowerName[14:34]: SortTypeByPopularity,
}

var _SortTypeNames = []string{
	_SortTypeName[0:14],
	_SortTypeName[14:34],
}

// SortTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SortTypeString(s string) (SortType, error) {
	if val, ok := _SortTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SortTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SortType values", s)
}

// SortTypeValues returns all values of the enum
func SortTypeValues() []SortType {
	return _SortTypeValues
}

// SortTypeStrings returns a slice of all String values of the enum
func SortTypeStrings() []string {
	strs := make([]string, len(_SortTypeNames))
	copy(strs, _SortTypeNames)
	return strs
}

// IsASortType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SortType) IsASortType() bool {
	for _, v := range _SortTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SortType
func (i SortType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SortType
func (i *SortType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SortType should be a string, got %s", data)
	}

	var err error
	*i, err = SortTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for SortType
func (i SortType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for SortType
func (i *SortType) UnmarshalText(text []byte) error {
	var err error
	*i, err = SortTypeString(string(text))
	return err
}

func (i SortType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *SortType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of SortType: %[1]T(%[1]v)", value)
	}

	val, err := SortTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
