// Code generated by "enumer -type=ItemAction -json -text -sql"; DO NOT EDIT.

package model

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _ItemActionName = "GiveTake"

var _ItemActionIndex = [...]uint8{0, 4, 8}

const _ItemActionLowerName = "givetake"

func (i ItemAction) String() string {
	if i < 0 || i >= ItemAction(len(_ItemActionIndex)-1) {
		return fmt.Sprintf("ItemAction(%d)", i)
	}
	return _ItemActionName[_ItemActionIndex[i]:_ItemActionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ItemActionNoOp() {
	var x [1]struct{}
	_ = x[Give-(0)]
	_ = x[Take-(1)]
}

var _ItemActionValues = []ItemAction{Give, Take}

var _ItemActionNameToValueMap = map[string]ItemAction{
	_ItemActionName[0:4]:      Give,
	_ItemActionLowerName[0:4]: Give,
	_ItemActionName[4:8]:      Take,
	_ItemActionLowerName[4:8]: Take,
}

var _ItemActionNames = []string{
	_ItemActionName[0:4],
	_ItemActionName[4:8],
}

// ItemActionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ItemActionString(s string) (ItemAction, error) {
	if val, ok := _ItemActionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ItemActionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ItemAction values", s)
}

// ItemActionValues returns all values of the enum
func ItemActionValues() []ItemAction {
	return _ItemActionValues
}

// ItemActionStrings returns a slice of all String values of the enum
func ItemActionStrings() []string {
	strs := make([]string, len(_ItemActionNames))
	copy(strs, _ItemActionNames)
	return strs
}

// IsAItemAction returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ItemAction) IsAItemAction() bool {
	for _, v := range _ItemActionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ItemAction
func (i ItemAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ItemAction
func (i *ItemAction) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ItemAction should be a string, got %s", data)
	}

	var err error
	*i, err = ItemActionString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for ItemAction
func (i ItemAction) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ItemAction
func (i *ItemAction) UnmarshalText(text []byte) error {
	var err error
	*i, err = ItemActionString(string(text))
	return err
}

func (i ItemAction) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *ItemAction) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of ItemAction: %[1]T(%[1]v)", value)
	}

	val, err := ItemActionString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
