// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ItemAction.
const (
	Give ItemAction = "give"
	Take ItemAction = "take"
)

// Valid indicates whether the value is a known member of the ItemAction enum.
func (e ItemAction) Valid() bool {
	switch e {
	case Give:
		return true
	case Take:
		return true
	default:
		return false
	}
}

// Defines values for ItemType.
const (
	Good    ItemType = "good"
	Service ItemType = "service"
)

// Valid indicates whether the value is a known member of the ItemType enum.
func (e ItemType) Valid() bool {
	switch e {
	case Good:
		return true
	case Service:
		return true
	default:
		return false
	}
}

// Defines values for SortType.
const (
	SortTypeCreatedAt  SortType = "created_at"
	SortTypePopularity SortType = "popularity"
)

// Valid indicates whether the value is a known member of the SortType enum.
func (e SortType) Valid() bool {
	switch e {
	case SortTypeCreatedAt:
		return true
	case SortTypePopularity:
		return true
	default:
		return false
	}
}

// Defines values for ListItemsParamsSort.
const (
	ListItemsParamsSortCreatedAt  ListItemsParamsSort = "created_at"
	ListItemsParamsSortPopularity ListItemsParamsSort = "popularity"
)

// Valid indicates whether the value is a known member of the ListItemsParamsSort enum.
func (e ListItemsParamsSort) Valid() bool {
	switch e {
	case ListItemsParamsSortCreatedAt:
		return true
	case ListItemsParamsSortPopularity:
		return true
	default:
		return false
	}
}

// CreateItemRequest defines model for CreateItemRequest.
type CreateItemRequest struct {
	// Action Whether the user offers or requests something
	Action      ItemAction `json:"action"`
	Description string     `json:"description"`
	Name        string     `json:"name"`

	// Type Type of barter item
	Type ItemType `json:"type"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Item defines model for Item.
type Item struct {
	// Action Whether the user offers or requests something
	Action ItemAction `json:"action"`

	// CreatedAt Item creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Description Detailed item description
	Description string `json:"description"`

	// Id Unique item identifier
	Id openapi_types.UUID `json:"id"`

	// Name Short item title
	Name string `json:"name"`

	// Type Type of barter item
	Type ItemType `json:"type"`

	// Views Number of item views
	Views int64 `json:"views"`
}

// ItemAction Whether the user offers or requests something
type ItemAction string

// ItemType Type of barter item
type ItemType string

// ItemsCursor Cursor for stable pagination
type ItemsCursor struct {
	CreatedAt *time.Time         `json:"createdAt,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Views     *int64             `json:"views,omitempty"`
}

// ListItemsResponse defines model for ListItemsResponse.
type ListItemsResponse struct {
	// Items List of items
	Items []Item `json:"items"`

	// NextCursor Cursor for fetching the next page; null if there is no next page
	NextCursor *ItemsCursor `json:"nextCursor,omitempty"`
}

// CursorCreatedAt defines model for CursorCreatedAt.
type CursorCreatedAt = time.Time

// CursorId defines model for CursorId.
type CursorId = openapi_types.UUID

// CursorViews defines model for CursorViews.
type CursorViews = int64

// Limit defines model for Limit.
type Limit = int

// SortType defines model for SortType.
type SortType string

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	// Sort Sorting mode for items list
	Sort ListItemsParamsSort `form:"sort" json:"sort"`

	// CursorCreatedAt Cursor creation timestamp in RFC3339 format.
	// Used together with `cursor_id` when `sort=created_at`.
	CursorCreatedAt *CursorCreatedAt `form:"cursor_created_at,omitempty" json:"cursor_created_at,omitempty"`

	// CursorViews Cursor views count.
	// Used together with `cursor_id` when `sort=popularity`.
	CursorViews *CursorViews `form:"cursor_views,omitempty" json:"cursor_views,omitempty"`

	// CursorId Cursor item ID used as a tie-breaker for stable pagination.
	CursorId *CursorId `form:"cursor_id,omitempty" json:"cursor_id,omitempty"`

	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListItemsParamsSort defines parameters for ListItems.
type ListItemsParamsSort string

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = CreateItemRequest
