basePath: /
definitions:
  http_api.ErrorResponse:
    properties:
      error:
        description: The error message
        type: string
    type: object
  model.Item:
    properties:
      action:
        $ref: '#/definitions/model.ItemAction'
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      type:
        $ref: '#/definitions/model.ItemType'
      views:
        type: integer
    type: object
  model.ItemAction:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - Give
    - Take
  model.ItemType:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - Good
    - Service
  model.UniversalCursor:
    properties:
      createdAt:
        example: "2026-03-04T12:00:00Z"
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      views:
        example: 120
        type: integer
    type: object
  transport.CreateItemRequest:
    properties:
      action:
        enum:
        - give
        - take
        type: string
      description:
        example: description
        type: string
      name:
        example: name
        type: string
      type:
        enum:
        - good
        - service
        type: string
    type: object
  transport.GetItemResponse:
    properties:
      cursor:
        allOf:
        - $ref: '#/definitions/model.UniversalCursor'
        description: Cursor for the next page
      items:
        description: List of items
        items:
          $ref: '#/definitions/model.Item'
        type: array
    type: object
info:
  contact: {}
  description: API for Barter Port
  title: Barter Port API
  version: 1.0.0
paths:
  /items:
    get:
      description: Fetch a list of items with optional sorting and pagination
      parameters:
      - description: Sort type (ByTime, ByPopularity)
        in: query
        name: sort_type
        required: true
        type: string
      - description: Creation time for cursor (ISO 8601 format)
        in: query
        name: created_at
        type: string
      - description: Views for cursor
        in: query
        name: views
        type: integer
      - description: UUID for cursor
        in: query
        name: id
        type: string
      - description: Maximum number of items to fetch
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of items and pagination cursor
          schema:
            $ref: '#/definitions/transport.GetItemResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/http_api.ErrorResponse'
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Get a list of items
      tags:
      - items
    post:
      consumes:
      - application/json
      description: Create a new item with the provided details
      parameters:
      - description: Create Item Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transport.CreateItemRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Create a new item
      tags:
      - items
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
