// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AvatarUploadResponse defines model for AvatarUploadResponse.
type AvatarUploadResponse struct {
	// AvatarUrl User avatar URL
	AvatarUrl AvatarUrl `json:"avatarUrl"`
}

// AvatarUrl User avatar URL
type AvatarUrl = string

// Bio User bio
type Bio = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// Me defines model for Me.
type Me struct {
	// AvatarUrl User avatar URL
	AvatarUrl *AvatarUrl `json:"avatarUrl,omitempty"`

	// Bio User bio
	Bio *Bio `json:"bio,omitempty"`

	// CreatedAt User registration timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Email User email
	Email string `json:"email"`

	// Id User ID
	Id UserId `json:"id"`

	// IsAdmin Whether the current user has admin access
	IsAdmin bool `json:"isAdmin"`

	// Name User name
	Name *Name `json:"name,omitempty"`
}

// Name User name
type Name = string

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	// AvatarUrl User avatar URL
	AvatarUrl *AvatarUrl `json:"avatarUrl,omitempty"`

	// Bio User bio
	Bio *Bio `json:"bio,omitempty"`

	// Name User name
	Name *Name `json:"name,omitempty"`
}

// User defines model for User.
type User struct {
	// AvatarUrl User avatar URL
	AvatarUrl *AvatarUrl `json:"avatarUrl,omitempty"`

	// Bio User bio
	Bio *Bio `json:"bio,omitempty"`

	// Id User ID
	Id UserId `json:"id"`

	// Name User name
	Name *Name `json:"name,omitempty"`
}

// UserId User ID
type UserId = openapi_types.UUID

// Id defines model for Id.
type Id = openapi_types.UUID

// UploadCurrentUserAvatarMultipartBody defines parameters for UploadCurrentUserAvatar.
type UploadCurrentUserAvatarMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// UpdateCurrentUserJSONRequestBody defines body for UpdateCurrentUser for application/json ContentType.
type UpdateCurrentUserJSONRequestBody = UpdateUserRequest

// UploadCurrentUserAvatarMultipartRequestBody defines body for UploadCurrentUserAvatar for multipart/form-data ContentType.
type UploadCurrentUserAvatarMultipartRequestBody UploadCurrentUserAvatarMultipartBody
