// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	ErrorCodeInternal       ErrorCode = "INTERNAL"
	ErrorCodeInvalidRequest ErrorCode = "INVALID_REQUEST"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidRequest:
		return true
	default:
		return false
	}
}

// Bio User bio
type Bio = string

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    ErrorCode `json:"code"`
	Message *string   `json:"message,omitempty"`
}

// Me defines model for Me.
type Me struct {
	// Bio User bio
	Bio *Bio `json:"bio,omitempty"`

	// CreatedAt User registration timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Email User email
	Email openapi_types.Email `json:"email"`

	// Id User ID
	Id UserId `json:"id"`

	// Name User name
	Name Name `json:"name"`
}

// Name User name
type Name = string

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	// Bio User bio
	Bio *Bio `json:"bio,omitempty"`

	// Name User name
	Name *Name `json:"name,omitempty"`
}

// User defines model for User.
type User struct {
	// Bio User bio
	Bio *Bio `json:"bio,omitempty"`

	// Id User ID
	Id UserId `json:"id"`

	// Name User name
	Name Name `json:"name"`
}

// UserId User ID
type UserId = openapi_types.UUID

// Id defines model for Id.
type Id = openapi_types.UUID

// UpdateCurrentUserJSONRequestBody defines body for UpdateCurrentUser for application/json ContentType.
type UpdateCurrentUserJSONRequestBody = UpdateUserRequest
