// Code generated by "enumer -type=SourceType -json -text -sql -transform=lower -trimprefix=SourceType"; DO NOT EDIT.

package enums

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _SourceTypeName = "offerreport"

var _SourceTypeIndex = [...]uint8{0, 11}

const _SourceTypeLowerName = "offerreport"

func (i SourceType) String() string {
	if i < 0 || i >= SourceType(len(_SourceTypeIndex)-1) {
		return fmt.Sprintf("SourceType(%d)", i)
	}
	return _SourceTypeName[_SourceTypeIndex[i]:_SourceTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SourceTypeNoOp() {
	var x [1]struct{}
	_ = x[SourceTypeOfferReport-(0)]
}

var _SourceTypeValues = []SourceType{SourceTypeOfferReport}

var _SourceTypeNameToValueMap = map[string]SourceType{
	_SourceTypeName[0:11]:      SourceTypeOfferReport,
	_SourceTypeLowerName[0:11]: SourceTypeOfferReport,
}

var _SourceTypeNames = []string{
	_SourceTypeName[0:11],
}

// SourceTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SourceTypeString(s string) (SourceType, error) {
	if val, ok := _SourceTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SourceTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SourceType values", s)
}

// SourceTypeValues returns all values of the enum
func SourceTypeValues() []SourceType {
	return _SourceTypeValues
}

// SourceTypeStrings returns a slice of all String values of the enum
func SourceTypeStrings() []string {
	strs := make([]string, len(_SourceTypeNames))
	copy(strs, _SourceTypeNames)
	return strs
}

// IsASourceType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SourceType) IsASourceType() bool {
	for _, v := range _SourceTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SourceType
func (i SourceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SourceType
func (i *SourceType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SourceType should be a string, got %s", data)
	}

	var err error
	*i, err = SourceTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for SourceType
func (i SourceType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for SourceType
func (i *SourceType) UnmarshalText(text []byte) error {
	var err error
	*i, err = SourceTypeString(string(text))
	return err
}

func (i SourceType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *SourceType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of SourceType: %[1]T(%[1]v)", value)
	}

	val, err := SourceTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
